### ISSUE TITLE
VQE and PEA tutorial help wanted

### ISSUE THREAD

**Issue by Konjkov** [quantumlib/OpenFermion#241]
Hello Ryan I just read your article https://arxiv.org/abs/1512.06860

Could you provide examples/tutorial of OpenFermion codes for VQE Experiment and  PEA Experiment
which results plotted on the FIG 3.

As far as I understand the OpenFermion functionality is enough for but on my own I could not write such code.

Best Vladimir.

**Comment by babbush** [comment]
Hi Vladimir,

In our plugin [OpenFermion-ProjectQ](https://github.com/quantumlib/OpenFermion-ProjectQ) we have [this demo](https://github.com/quantumlib/OpenFermion-ProjectQ/blob/master/examples/openfermionprojectq_demo.ipynb) which shows how to perform UCC. We do not actually have a phase estimation tutorial. However, there are routines in ProjectQ for Trotterization so it should not be too difficult to build.

Note that in order to remain "platform agnostic", i.e. not preference IBM QISKit or ProjectQ or Microsoft Q# or Rigetti Forest, the core of OpenFermion is really about Hamiltonian manipulation and then we have plugins which help to compile circuits. Google intends to release an additional OpenFermion plugin before the summer that has many more routines but I can't say more at this point.

Since we already have an issue open about adding demos, I am going to add a note that you'd like to see a PEA demo but I am going to close this issue.
