### ISSUE TITLE
Generalize __add__ and __eq__ methods of PolynomialTensor

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#274]
As discussed in #240, we should be able to add and compare PolynomialTensors with different sets of keys (if the key is not present then it counts as the zero tensor). Currently, attempting these operations raises an error.

**Comment by idk3** [comment]
+1, closed the old issue. The only thing remaining from the old issue is to add new tests addressing Python 2/3 differences. Importing dict from builtins is one good way to address this for the class, but we could also do something more order independent (with the downside perhaps of more time).

**Comment by singular-value** [comment]
Okay, I am working on this issue.

I wrote https://github.com/singular-value/OpenFermion/commit/df496de3dc33b145bab2af5056fdeb7596b42d56, which updates `__eq__`. In order to allow allow comparisons between `PolynomialTensor`s with different keys, I needed to convert the keys to sets. This also happened to take care of the ordering-sensitivity, so I didn't end up needing to import dict from builtins.

Will make the pull request when I also update __add__, __sub__, and __mul__ later this week.

**Comment by singular-value** [comment]
@kevinsung and @idk3, quick clarification question. Did you resolve in #240 that:

- Attempting to add, subtract, and multiply `PolynomialTensor`s of differing keys should always raise a `ValueError` (instead of the current `TypeError`)
OR that
- Attempting to add, subtract, and multiply `PolynomialTensor`s of differing keys should be permissible iff the differing keys correspond to zero-arrays. If the differing keys correspond to non-zero arrays then we should raise a `ValueError`.
OR that
- Attempting to add, subtract, and multiply `PolynomialTensor`s of differing keys should always be permitted. Differing keys should be incorporated into the result.

**Comment by kevinsung** [comment]
The last one (everything should always be allowed). A lack of key should be considered the presence of a zero tensor (array of all zeros).
