### ISSUE TITLE
Optimize get_linear_qubit_operator

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#339]
This is a place where speed is critical. I just wanted to record here some suggestions that came up so they're not lost:
- As mentioned at #335 , one of the loops can probably be parallelized
- We could use Cython or the Numpy C API or something like that

**Comment by jarrodmcc** [comment]
Both loops can likely be parallelized, but with different strategies.  It's easier to parallelize over the sum between terms, then do a reduce operation, but that has a higher memory overhead and only speeds up QubitOperators with multiple terms.  The inner loop may actually be a bit tricky due to operations touching the same part of memory.

**Comment by sheilaliuxl** [comment]
I guess the inner loop is a good candidate for Cython, while the outer one is good for multithreading.

**Comment by jarrodmcc** [comment]
At some point we will want C++, Cython, or other bindings to optimize some of the routines.  The first addition of this will be the major hurdle, because we have to change the CI, build system, testing etc, but once it's there it has the potential to lower the barrier for others.  For any C++ change we make, I think the Python simulator should be left in place so that if the build fails on someone's system it can be defaulted back to.  Projectq worked this way and I think it's a reasonable choice.

**Comment by babbush** [comment]
Did @sheilaliuxl 's pull requests sufficiently close this issue?

**Comment by sheilaliuxl** [comment]
@babbush Inner loop (C(ython)) is still a TODO item, while the outer loop is done in #357.
