### ISSUE TITLE
Recommend virtualenv instead of pip install --user

### ISSUE THREAD

**Issue by DanielSank** [quantumlib/OpenFermion#36]
The README recommends the `--user` flag for pip install. This is generally a very good idea, but it seems like an attempt to avoid the generally accepted "right" way to isolate installed python packages from the system python, namely with [`virtualenv`](https://virtualenv.pypa.io/en/stable/).

**Comment by babbush** [comment]
We actually provide a docker image which is a preconfigured virtual environment essentially. I'd like to hear some other opinions on this one because I am of the opinion that we want to avoid unnecessarily complicated install instructions, especially for those who are avoiding a develop install and are likely to be less sophisticated users. In other words, I think that most people who know how to use virtual environments aren't going to need our install instructions in the first place.

**Comment by DanielSank** [comment]
> we want to avoid unnecessarily complicated install instructions

Agreed. It's unfortunate that virtualenv is still unnecessarily complicated, but I guess that's the reality of life.

> especially for those who are avoiding a develop install and are likely to
> be less sophisticated users.

So, in that case, why recommend the `--user` flag in the first place? Is that to avoid having to `sudo`?

> In other words, I think that most people who know how to use virtual environments
> aren't going to need our install instructions in the first place.

Well, see issue #37...

**Comment by babbush** [comment]
Yes, its so they don't need to use sudo (we certainly don't want that). Regarding https://github.com/quantumlib/OpenFermion/issues/38, I think the solution is to (as you say) remind people to first upgrade pip. I will do this on my next pull request sometime this weekend.
