### ISSUE TITLE
Can't build openfermion image using dockerfile using docker toolbox on windows 10 Home

### ISSUE THREAD

**Issue by irfankhan10** [quantumlib/OpenFermion#385]
If I run openfermion build command on the unedited dockerfile (ubuntu version not specified), I get the error:
"Package 'ipython-notebook has no installation candidate" (error code: 100)

If run openfermion build command on an edited dockerfile (ubuntu 16:04 version specified), I get the error:
"Cannot uninstall 'ipython'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall." (error code: 1)

**Comment by babbush** [comment]
@irfankhan10 sorry we never responded to this - it has been a very busy period for us developers as a consequence of releasing OpenFermion-Cirq a couple weeks back. Did you actually find a solution to this problem or does it still persist? If you did find a solution would you mind sharing so that others who encounter the issue might benefit?

**Comment by irfankhan10** [comment]
Hi,

I don't have a solution yet, but I have an idea that I will try tonight.

**Comment by kevinsung** [comment]
@irfankhan10 Can you try again with the latest dockerfile? It was updated recently in #441.

**Comment by babbush** [comment]
I will close for now since we've made substantial changes to the Docker.
