### ISSUE TITLE
UCCSD error?

### ISSUE THREAD

**Issue by sammcardle30** [quantumlib/OpenFermion#451]
Hi all,

I've been trying to use the UCCSD ansatz generating functions, and have run into a couple of problems that I was hoping you could help me with. I've tried generating general UCCSD and singlet UCCSD operators using the functions supplied, for H2 and LiH. When I use the function uccsd_singlet_get_packed_amplitudes() I get the following error (for LiH, similar for H2):

> Traceback (most recent call last):
>   File "/Users/sam/Documents/OpenFermion/UCCtest.py", line 48, in <module>
>     packed_amps = uccsd_singlet_get_packed_amplitudes(ccsd_single_amps, ccsd_double_amps, num_qubits, num_electrons)
>   File "/Users/sam/.local/lib/python3.6/site-packages/openfermion/utils/_unitary_cc.py", line 184, in uccsd_singlet_get_packed_amplitudes
>     singles.append(single_amplitudes[virtual_up, occupied_up])
> IndexError: index 4 is out of bounds for axis 0 with size 4

If I instead try a general UCCSD calculation using the function uccsd_generator(), I get an operator that looks correct for LiH. However, if I try this function with H2, it returns 0, instead of the correct UCCSD operator.

I've attached my code below; please could you let me know if there's something that I'm doing wrong in both of these instances?

```
import openfermion
import openfermionpyscf
from openfermion.hamiltonians import MolecularData
from openfermionpyscf import run_pyscf
from openfermion.ops import FermionOperator, QubitOperator
from openfermion.transforms import get_fermion_operator
from openfermion.utils import (uccsd_singlet_get_packed_amplitudes,
                               uccsd_singlet_generator, uccsd_generator,
                               uccsd_convert_amplitude_format)
import numpy as np

singlet_bool = True # Set general UCCSD or singlet UCCSD.

bond_len = 1.45
atom_1 = 'Li'
atom_2 = 'H'
basis = 'sto3g'
multiplicity = 1
charge = 0

coordinate_1 = (0.0, 0.0, 0.0)
coordinate_2 = (0.0, 0.0, bond_len)
geometry = [(atom_1, coordinate_1), (atom_2, coordinate_2)]

molecule = MolecularData(geometry, basis, multiplicity,
                         charge, description='Test')

scf = True      # Hartree-Fock.
mp2 = True      # Moller-Plesset 2.
cisd = True     # Configuration interaction singles and doubles.
ccsd = True     # Coupled cluster singles and doubles.
fci = True      # Full configuration interaction.

calculated_molecule = run_pyscf(molecule, scf, mp2, cisd, ccsd, fci)

if ccsd:
    ccsd_single_amps = calculated_molecule.ccsd_single_amps
    ccsd_double_amps = calculated_molecule.ccsd_double_amps

num_electrons = calculated_molecule.n_electrons
num_qubits = 2*calculated_molecule.n_orbitals

if singlet_bool:
    # Get singlet UCCSD generator.
    packed_amps = uccsd_singlet_get_packed_amplitudes(ccsd_single_amps,  ccsd_double_amps, num_qubits, num_electrons)
    ucc_sing = uccsd_singlet_generator(packed_amps, num_qubits, num_electrons)
    print(ucc_sing)

else:
    # Get general UCCSD operator.
    ucc_op = uccsd_generator(ccsd_single_amps, ccsd_double_amps)
    print(ucc_op)
```

Thanks for your help,

Sam

**Comment by kevinsung** [comment]
Sam, I don't have a solution, but the issue has to do with the shape of the arrays `calculated_molecule.ccsd_single_amps` and `calculated_molecule.ccsd_double_amps`. The molecule in your example, LiH at bond length 1.45, happens to be one of the pre-loaded datasets that ships with OpenFermion, so we can see what happens if we use that data:
```
from openfermion import MolecularData

bond_len = 1.45
atom_1 = 'Li'
atom_2 = 'H'
basis = 'sto-3g'
multiplicity = 1
charge = 0

coordinate_1 = (0.0, 0.0, 0.0)
coordinate_2 = (0.0, 0.0, bond_len)
geometry = [(atom_1, coordinate_1), (atom_2, coordinate_2)]

calculated_molecule = MolecularData(geometry, basis, multiplicity,
                         charge, description='1.45')

calculated_molecule.load()

print(calculated_molecule.ccsd_single_amps.shape)
print(calculated_molecule.ccsd_double_amps.shape)
```
This gives
```
(12, 12)
(12, 12, 12, 12)
```
which are the shapes expected by `uccsd_singlet_get_packed_amplitudes`. If we run your code, however, which calculates the molecular data using OpenFermion-PySCF, as follows:
```
import openfermionpyscf
from openfermion.hamiltonians import MolecularData
from openfermionpyscf import run_pyscf

singlet_bool = True # Set general UCCSD or singlet UCCSD.

bond_len = 1.45
atom_1 = 'Li'
atom_2 = 'H'
basis = 'sto3g'
multiplicity = 1
charge = 0

coordinate_1 = (0.0, 0.0, 0.0)
coordinate_2 = (0.0, 0.0, bond_len)
geometry = [(atom_1, coordinate_1), (atom_2, coordinate_2)]

molecule = MolecularData(geometry, basis, multiplicity,
                         charge, description='Test')

scf = True      # Hartree-Fock.
mp2 = True      # Moller-Plesset 2.
cisd = True     # Configuration interaction singles and doubles.
ccsd = True     # Coupled cluster singles and doubles.
fci = True      # Full configuration interaction.

calculated_molecule = run_pyscf(molecule, scf, mp2, cisd, ccsd, fci)

print(calculated_molecule.ccsd_single_amps.shape)
print(calculated_molecule.ccsd_double_amps.shape)
```
we get
```
(4, 2)
(4, 4, 2, 2)
```
I don't yet have an explanation for this discrepancy, but perhaps @jarrodmcc , @babbush , or @sunqm can explain.

**Comment by babbush** [comment]
@jarrodmcc any idea what's going on here?

**Comment by sunqm** [comment]
Is the problem related to the spin-orbital vs spatial-orbital representation? The uccsd amplitudes returned by pyscf are based on spatial orbitals. The t1 amplitude has two components, one for spin-up, the other for spin-down.

**Comment by vincentelfving** [comment]
I ran into the same problem as @sammcardle30 (have you made any progress?), when I try to create a UCCSD ansatz for any pySCF generated MolecularData object constructed via OpenFermion-PySCF.

After digging a bit deeper, I figured out the following:

As @kevinsung correctly pointed out, the `openfermion.utils._unitary_cc.py` function `uccsd_singlet_get_packed_amplitudes` assumes as input for the single_amplitudes a NxN numpy array and for the double_amplitudes a NxNxNxN numpy array where N is the number of spin-orbitals.

However, the `MolecularData` file constructed with pyscf has single_amplitudes of the shape AxB and the double_amplitudes have AxAxBxB, where A+B is the total number of spatial orbitals, and 2B is the total number of electrons. This is, as @sunqm partially pointed out, because
1) pyscf's amplitudes are based on spatial orbitals
2) pyscf's amplitudes only take into account the excitations going from occupied to virtual (I think)
The reason, I think, is because with this notation pyscf is using, it is already compacted to make sense for singlet UCCSD. 

In my notation above, B is the number of _occupied spatial_ orbitals (each filled with an alpha and beta electron), and A is the number of _virtual spatial_ orbitals. 2*(A+B) is the total number of spinorbitals. The single_amplitudes will have AxB possible excitation coefficients (A virtual spaces to choose from, coming form B occupied spatial orbitals), and similarly for the double_amplitudes with AxAxBxB possibilities.

In essence, I think this is also what the `uccsd_singlet_get_packed_amplitudes` achieves right? it takes as an input the complete spinorbital matrix elements NxN and NxNxNxN and packs it into a compact list which "are relevant to singlet UCCSD, in an order suitable for use with the function `uccsd_singlet_generator`".

So, there must be a way to convert the pySCF CCSD amplitudes to the packed_amplitudes format to use in openfermion's `uccsd_singlet_generator`. Unfortunately, my inexperience with chemistry prohibits me from easily writing such a helpter-function, but I am more than willing to help out!

I think having a helper-function like this, would actually make it possible to generate the uccsd singlet generator for an arbitrary molecule the user made himself, and therefore it is of significant interest. As it stands now, a user can not generate a UCCSD ansatz for their own generated molecule directly. @babbush thoughts? And maybe this should this be linked to OpenFermion-PySCF, or should the converter/importer/helper-function be part of openfermion.utils?

**Comment by babbush** [comment]
I believe that @sunqm may have just fixed this with [PR #42](https://github.com/quantumlib/OpenFermion-PySCF/pull/42) on OpenFermion-PySCF. Does this solve your problem?

**Comment by vincentelfving** [comment]
Thanks a lot @sunqm ! there seems to be just a small typo I commented on at [PR # 42](https://github.com/quantumlib/OpenFermion-PySCF/pull/42)

With that fixed, the above problem as stated is also fixed as there are no code errors anymore, the `uccsd_singlet_get_packed_amplitudes` can now accept ccsd amplitudes generated from `run_pyscf` as they are in the right .shape.

I have opened a  [new Issue](https://github.com/quantumlib/OpenFermion-PySCF/issues/43) on Openfermion-PySCF which is somewhat related to this Issue and it's a problem these same users might run into.

**Comment by babbush** [comment]
How do you think [PR 44](https://github.com/quantumlib/OpenFermion-PySCF/pull/44) on OpenFermion-PySCF addressed the issue?

**Comment by vincentelfving** [comment]
@babbush perfect, I think both Issues can be closed:)

**Comment by babbush** [comment]
Great! Thanks!

**Comment by Kee-Wang** [comment]
Hi everyone, I was wondering is anyone able to get correct result dimension now? The `ccsd_single_amps` and `ccsd_double_amps` still gives me AB and AABB dimension rather than NN and NNNN dimension such that they are not able to be feed into `uccsd_generator`. (I still haven't found any solution to this problem after reading threads, or probably I missed something?)

**Comment by vincentelfving** [comment]
Hi @Kee-Wang ! which `MolecularData` input object are you using? In the old formatting, the `MolecularData` was in AB and AABB dimension. In this thread there are links PR 42 and PR 44 referring to a fix in OpenFermion-PySCF (not OpenFermion itself) to generate NN and NNNN formatted CCSD amps. 

I suggest you try re-making your `MolecularData` with the latest version of OpenFermion-PySCF and that should work as an input to `uccsd_generator`.

**Comment by ChrisW918** [comment]
Hi guys, I got a question that what is the return of uccsd_generator. Is that a circuit under uccsd ansatz? If so, how can I create a cost_function to apply optimizer and get the ground state energy of an arbitary molecule? It seems the present tutorial online is outdated and not get Cirq included.

**Comment by obriente** [comment]
Hi Chris, the function generates a FermionOperator which would correspond to the cluster operator with the input singles and doubles operators. This still needs to be converted into a quantum circuit via exponentiation / Trotterization (see the routines in openfermion.circuits.trotter), and then the cost function for the Hamiltonian needs to be implemented separately.

Cheers,

Tom.

**Comment by ChrisW918** [comment]
Thanks for reply, Tom @obriente. Is it work if I apply Jordan_Wigner as qubit transformer than trotter? And then convert the hamiltonian to sparse_hamiltonian using _get_sparse_operator( )_, which enables to return energy as output. Actually I posted my code in issue #732 , could you take a look at it.
