### ISSUE TITLE
Couldn't find OpenFermion.Hamiltonians Pkg

### ISSUE THREAD

**Issue by basernapairs** [quantumlib/OpenFermion#698]
Hii i want try this ex. code, but still error when after adding OpenFermion pkg, so where Hamiltonians  ?

![image](https://user-images.githubusercontent.com/75351310/103191392-c433d380-490f-11eb-84d8-fb268893db7a.png)

![image](https://user-images.githubusercontent.com/75351310/103191479-25f43d80-4910-11eb-8c52-7dd3590b0aa6.png)

**Comment by ncrubin** [comment]
Hi @basernapairs ,  I believe this problem is related to where PyCall is looking for our python packages.  PyCall defaults to a python build that comes in Conda.jl.  Following the docs on PyCall I was able to set up a new environment, install openfermion, point my PyCall build to that envs python, and then successfully import OpenFermion.

I used the following after making a new env with a fresh OpenFermion build.
```
julia> ENV["PYTHON"]="<path to your python3.x"
pkg> add PyCall  # or Pkg.build("PyCall") if you have it already
```
Then close your julia console. Reopen and try importing OpenFermion.  I was able to see the modules from inside the Julia console so I assume they are usable.
