### ISSUE TITLE
Would it be helpful adding first quantization methods to resource estimates?

### ISSUE THREAD

**Issue by PabloAMC** [quantumlib/OpenFermion#767]
I've seen that OpenFermion now includes some cost estimates: https://github.com/quantumlib/OpenFermion/tree/master/src/openfermion/resource_estimates

They are from the most up-to-date rank-factorization methods, but I could help with the first-quantization methods. Would this be useful for the library maintainers?

I already have coded a version of the qubitization technique, and could probably "easily" do the equivalent one for the interaction picture method. I was thinking of having this in my own library TFermion, but it may be more useful for the community to have it directly here now that we have started with the Sparsification and Rank Factorization techniques.

If we want to add this up, a follow-up question is: do we want to include the cost of preparing the initial state, since in this case it would not be a computational basis state?

**Comment by babbush** [comment]
I think that would be helpful. I assume you are referring to the estimates from (https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.2.040332)?

I don't think the initial state preparation is going to be so important since one can anti-symmeterize the initial states with very significantly less complexity than the cost of phase estimation, so it is essentially a negligible additive factor. This is possible using the techniques from https://www.nature.com/articles/s41534-018-0071-5

**Comment by PabloAMC** [comment]
Yes, I am referring to that 🙂. 

Ok, give me a couple of weeks (as I am a bit busy right now) and I'll get it done.

**Comment by fdmalone** [comment]
These costs are incorporated in [qualtran](https://github.com/quantumlib/Qualtran/tree/main/qualtran/bloqs/chemistry/pbc/first_quantization)
