### ISSUE TITLE
BUG: Decoding error in setup.py on Windows.

### ISSUE THREAD

**Issue by nonhermitian** [quantumlib/OpenFermion#82]
Currently, installing OpenFermion on Windows with Python 3 (have not checked on Py2) fails due to a decoding error in the opening of `README.rst` for the long description:

```python
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    long_description = open('README.rst').read()
  File "C:\Users\J44364\AppData\Local\Continuum\Anaconda3\lib\encodings\cp1252.p
y", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5418: cha
racter maps to <undefined>
```
this is fixed by adding `encoding="utf-8"` as an argument to `open`.

**Comment by babbush** [comment]
Thanks! We'll look into this. Unfortunately because the electronic structure package dependancies (Psi4 and PySCF) are only supported on mac and linux, we do not yet fully support Windows. For those running on Windows we would recommend using the Docker installation.

However, it is nice to know that the core library installs at all Windows! This does seem like a fairly easy issue to address.

**Comment by nonhermitian** [comment]
That should probably be mentioned in the readme then.  Having been doing open source quantum stuff for a while now, I know that Windows support is kind of a requirement for wide acceptance.  Sadly, it is also a pain in the butt.
